var firstIndustryList = [
    {
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    }
];
var secondIndustryList = [
    {
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    }
];
var thirdIndustryList = [
    {
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    },{
        name:"机器视觉",
        selected:false,
    }
];

export {firstIndustryList, secondIndustryList, thirdIndustryList};